"""
AES-256-GCM Encryption Handler for QuantumShieldFL

Provides authenticated encryption/decryption of federated learning
model updates using keys generated by the BB84 QKD protocol.

Uses AES-256-GCM which provides both confidentiality and integrity:
- Confidentiality: Nobody can read the encrypted model updates
- Integrity: Any tampering with the ciphertext is detected via the auth tag
"""

import os
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
import config


class AESCipher:
    """
    AES-256-GCM authenticated encryption handler.
    
    Encrypts serialized model parameters before transmission and
    decrypts received ciphertext using QKD-derived keys.
    """

    def __init__(self, key: bytes = None):
        """
        Initialize the cipher with an optional key.
        
        Args:
            key: 32-byte (256-bit) encryption key from QKD.
                 If None, must be provided in encrypt/decrypt calls.
        """
        self.key = key
        if key is not None:
            assert len(key) == config.AES_KEY_SIZE, (
                f"Key must be {config.AES_KEY_SIZE} bytes, got {len(key)}"
            )

    def encrypt(self, plaintext: bytes, key: bytes = None) -> dict:
        """
        Encrypt data using AES-256-GCM.
        
        Args:
            plaintext: Data to encrypt (serialized model parameters)
            key: Encryption key (uses stored key if None)
            
        Returns:
            dict with:
                - ciphertext: Encrypted data bytes
                - nonce: Random nonce used (12 bytes)
                - encrypted_size: Size of ciphertext in bytes
        
        Note: GCM mode appends a 16-byte authentication tag to ciphertext.
        """
        key = key or self.key
        if key is None:
            raise ValueError("No encryption key provided")
        
        assert len(key) == config.AES_KEY_SIZE, (
            f"Key must be {config.AES_KEY_SIZE} bytes, got {len(key)}"
        )
        
        # Generate random nonce
        nonce = os.urandom(config.AES_NONCE_SIZE)
        
        # Create AESGCM cipher and encrypt
        aesgcm = AESGCM(key)
        ciphertext = aesgcm.encrypt(nonce, plaintext, None)
        
        return {
            "ciphertext": ciphertext,
            "nonce": nonce,
            "encrypted_size": len(ciphertext),
        }

    def decrypt(self, ciphertext: bytes, nonce: bytes, key: bytes = None) -> bytes:
        """
        Decrypt data using AES-256-GCM.
        
        Args:
            ciphertext: Encrypted data (includes GCM auth tag)
            nonce: Nonce used during encryption
            key: Decryption key (uses stored key if None)
            
        Returns:
            bytes: Decrypted plaintext
            
        Raises:
            cryptography.exceptions.InvalidTag: If ciphertext was tampered with
                or wrong key is used
        """
        key = key or self.key
        if key is None:
            raise ValueError("No decryption key provided")
        
        aesgcm = AESGCM(key)
        plaintext = aesgcm.decrypt(nonce, ciphertext, None)
        
        return plaintext


def encrypt_model_update(serialized_params: bytes, key: bytes) -> dict:
    """
    Convenience function to encrypt serialized model parameters.
    
    Args:
        serialized_params: Output from model.serialize_model_params()
        key: QKD-derived encryption key
        
    Returns:
        dict with ciphertext, nonce, and metadata
    """
    cipher = AESCipher(key)
    result = cipher.encrypt(serialized_params)
    result["original_size"] = len(serialized_params)
    return result


def decrypt_model_update(ciphertext: bytes, nonce: bytes, key: bytes) -> bytes:
    """
    Convenience function to decrypt received model parameters.
    
    Args:
        ciphertext: Encrypted model update
        nonce: Nonce from encryption
        key: QKD-derived decryption key
        
    Returns:
        bytes: Serialized model parameters (ready for deserialization)
    """
    cipher = AESCipher(key)
    return cipher.decrypt(ciphertext, nonce)
